### ISSUE TITLE
[disassembler]: decode bug in LD [rp],(Mmm)

### ISSUE THREAD

**Issue by evolutional** [breakintoprogram/agon-projects#8] opened 2023-03-30 20:00 UTC
https://github.com/breakintoprogram/agon-projects/blob/e8a375c1bc45061b88fea39070b5b4bbe5de5dc1/C/Disassembler/main.c#L779

Little copy-pasta bug here, should be:

```
sprintf(t, "LD %s,(&%06X)",  t_rp[0][p], decodeWord(address, opcode));
```

**Comment by breakintoprogram** [comment] 2023-06-30 12:41
Marking this as 'Won't Do' as it is a duplicate of #9

**Closed as completed by breakintoprogram** 2023-06-30 12:41 UTC
Labels: duplicate
